### ISSUE TITLE
[Bug] Getting Sponsored results from Whoogle recently

### ISSUE THREAD

**Issue by githupper** [benbusby/whoogle-search#871] opened 2022-10-29 17:54 UTC
Recently I'm getting sponsored results from Whoogle

This is how I can replicate the issue reliably.

1. Search for X mobile company. Whoogle does not show any sponsored results.

2. Search for the same X company but append 5G. Whoogle does not show any sponsored results.

3. Search for X company again. This time first page is flooded with Sponsored results.

4. Clear browser cache. No more sponsored results. 

5. Repeat step 1 to 3 again and sponsored results will up again.

Previously Whoogle never show any type of sponsored results now matter how I search. Now I can duplicate this on both Android and iOS (via Firefox Focus) reliably. 

Any idea why it happen?

**Comment by githupper** [comment] 2022-10-29 18:05
![image](https://user-images.githubusercontent.com/25658765/198846491-41d87540-9743-4d95-9f74-3450a0742432.png)

**Comment by benbusby** [comment] 2022-10-31 18:39
Interesting. Looks like Google updated the way that they're serving ad content, so the Whoogle ad filter needs to get updated. I'll try to push an update to fix this soon.

**Comment by benbusby** [comment] 2022-10-31 18:56
@githupper are you using a specific instance when you see this? I haven't been able to replicate with any of my instances yet, but I'll keep trying. I'm curious if it's a region-specific thing.

**Comment by benbusby** [comment] 2022-10-31 19:03
Never mind, I found a way to reproduce it. It should be fixed now. Thanks for reporting!

**Closed** 2022-10-31 19:03 UTC

**Comment by githupper** [comment] 2022-11-01 03:04
And thank you for fixing this so quickly! Appreciate that!
