### ISSUE TITLE
[BUG] EU consent enforced, no more pending period

### ISSUE THREAD

**Issue by Suika** [benbusby/whoogle-search#311] opened 2021-05-14 02:03 UTC
**Describe the bug**
Time to accept the overlords has come. #243 is now useless, there is no more waiting period.
If you block js, you are instantly sent to the consent page. Whatever you do, won't change it.
If you have the JS enabled, there is some background worker magic happening, but also a pain to extract.
So the only way now, is to set the cookie to something that is generated.

Example url is `https://consent.google.de/ml?continue=https://www.google.de/&gl=DE&pc=shp&hl=de&src=1`, any change outside `continue` will error out the consent page.
`YES+cb.20210509-17-p0.de+F+678` is an example with everything set to no.
`YES+cb.20210509-17-p0.de+FX+678` is at least one or all parts accepted
Can be shortened to `YES+1`, but probably shouldn't.

https://github.com/benbusby/whoogle-search/blob/develop/app/request.py#L228 needs to be changed.

¯\\_(ツ)_/¯ It's only a matter of time untill you have to scan your subdermal chip to be able to search in the future.

**To Reproduce**
1. Be in EU
2. Use whoogle
2.1. Or deactiavate js, delete cookies and access google 
3. See error

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [X] Version [v0.4.1]
- [ ] Not sure

**Desktop (please complete the following information):**
 - doesn't matter

**Smartphone (please complete the following information):**
 - doesn't matter

**Additional context**
#243 was a way to circumvent the agreement, but it no longer works.

**Comment by ra-pha** [comment] 2021-05-14 04:54
Same problem here on 0.4.1

Further problem is that clicking "I agree" doesn't do anything.

If I want to adjust consent settings then a new tab opens with an error 400.

**Comment by Akruidenberg** [comment] 2021-05-14 05:07
Same here

**Comment by bergfex71** [comment] 2021-05-14 05:11
Confirmed.

**Comment by joonas-fi** [comment] 2021-05-14 05:34
I must admit the bug description is confusing to me (waiting period? JavaScript disabled?), but if it boils down to "Whoogle doesn't work, because it is showing Google cookie consent dialog whose 'I agree' button doesn't work", then yes, I am experiencing the same issue.

**Comment by JorelAli** [comment] 2021-05-14 06:35
I guess I'll join the list of people dealing with this issue as well!

**Comment by girlwithnoname** [comment] 2021-05-14 06:37
Confirmed. Modifying request.py with "YES+cb.20210509-17-p0.de+FX+678" works indeed. Thanks!

**Comment by milachevalier** [comment] 2021-05-14 07:21
FX agrees to tracking. Modifying it to just F seems to consent with 'no' to personalized stuff. Isn't that the better option for something like whoogle?

**Comment by milachevalier** [comment] 2021-05-14 07:26
Any idea what the parameters mean? The format has changed from #243 

Now it's YES+cb.[date]-[xx]-p0.en+F+[xxx] 

The three digit xxx is carried over from the 'pending-xxx' cookie. 
Any guess on what the two digit xx mean?

**Comment by girlwithnoname** [comment] 2021-05-14 07:27
Well, does tracking work? I assumed it does not and thus that the "cookie" is a fake cookie. I might be wrong though and will try it with the non-tracking option.

**Comment by LivingWithHippos** [comment] 2021-05-14 08:15
> Any guess on what the two digit xx mean?

I get 0 when I accept all and 17 for any other combination so I suppose it's that

**Comment by a1ad** [comment] 2021-05-14 12:30
Yup same here

**Comment by atropos112** [comment] 2021-05-14 12:33
Can't the cookies be accepted and then somehow corrupted to not do the tracking ?

**Comment by Suika** [comment] 2021-05-14 14:48
> 
> 
> Can't the cookies be accepted and then somehow corrupted to not do the tracking ?

Nope, it has to be `YES+1` or any number. The number is random.

**Comment by a1ad** [comment] 2021-05-14 15:39
So no workaround?

**Comment by gripped** [comment] 2021-05-14 16:18
> So no workaround?

The fix is in this thread ?
Modify line 216 of app/request.py to:
```
            'CONSENT': 'YES+cb.20210509-17-p0.de+F+678'
```

**Comment by a1ad** [comment] 2021-05-14 16:20
> > So no workaround?
> 
> The fix is in this thread ?
> Modify line 216 of app/request.py to:
> 
> ```
>             'CONSENT': 'YES+cb.20210509-17-p0.de+F+678'
> ```
> 
> Edit: And restart whoogle.

Oh, ok. And for the docker users?

**Comment by LivingWithHippos** [comment] 2021-05-14 16:30
> > > So no workaround?
> > 
> > 
> > The fix is in this thread ?
> > Modify line 216 of app/request.py to:
> > ```
> >             'CONSENT': 'YES+cb.20210509-17-p0.de+F+678'
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > Edit: And restart whoogle.
> 
> Oh, ok. And for the docker users?

You can either create a new Dockerfile which manually copies your custom `request.py` file (will survive container recreation, may interfere with future code update) or use `docker ps | grep whoogle` to get the container ID and then `docker exec -it containerID /bin/bash` and then edit with sed or awk the file (won' t survive container recreation but won't interfere with future updates). I'm going to try and then write more detailed steps.

**Comment by LivingWithHippos** [comment] 2021-05-14 17:32
`sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` launched inside the container will replace it and I can confirm that restarting the container fixes the error.

You can probably use docker exec to do something like `docker exec -d whoogle_container_name  sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` (untested)

**Comment by a1ad** [comment] 2021-05-14 17:42
> You can probably use docker exec to do something like `docker exec -d whoogle_container_name sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` (untested)

Confirmed

**Comment by tiagofreire-pt** [comment] 2021-05-14 20:44
> sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py

Confirmed, using the docker console with root privileges. Restarting the docker container is a must after executing this substitution.

Thanks, @LivingWithHippos !

**Comment by nandor-magyar** [comment] 2021-05-14 22:52
I have built an image using the proposed modifications. The issue is gone.

**Comment by eddydc** [comment] 2021-05-15 07:13
What with the official docker images which syndock/portainer/ouroboros depends on?

**Comment by vasilache1** [comment] 2021-05-15 12:43
> `sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` launched inside the container will replace it and I can confirm that restarting the container fixes the error.
> 
> You can probably use docker exec to do something like `docker exec -d whoogle_container_name sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` (untested)

Will this modification be added to master request.py ?

**Comment by eshadepunkt** [comment] 2021-05-15 13:29
> 
> 
> `sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` launched inside the container will replace it and I can confirm that restarting the container fixes the error.
> 
> You can probably use docker exec to do something like `docker exec -d whoogle_container_name sed -i "/'CONSENT':/ s/PENDING+999/YES+cb\.20210514-17-p0\.de+F+678/" /whoogle/app/request.py` (untested)

Worked for me. Thanks alot!

**Comment by joonas-fi** [comment] 2021-05-15 13:35
Workaround for making a Docker image:

Make a temp directory and write `Dockerfile`:
```
FROM benbusby/whoogle-search:latest

RUN sed -i "/'CONSENT':/ s/PENDING+999/YES+cb.20210514-17-p0.de+F+678/" /whoogle/app/request.py
```
(credit @LivingWithHippos)

Then run `docker build -t benbusby/whoogle-search:workaround .` to build this image. It is now runnable.

Now you can `docker run ... benbusby/whoogle-search:workaround`

**Comment by eddydc** [comment] 2021-05-17 08:21
As I am not feeling comfortable doing the above manual steps in my Synology docker environment, I was wondering an updated docker image would be available.

**Comment by bruvv** [comment] 2021-05-17 10:55
> 
> 
> Workaround for making a Docker image:
> 
> Make a temp directory and write `Dockerfile`:
> 
> ```
> FROM benbusby/whoogle-search:latest
> 
> RUN sed -i "/'CONSENT':/ s/PENDING+999/YES+cb.20210514-17-p0.de+F+678/" /whoogle/app/request.py
> ```
> 
> (credit @LivingWithHippos)
> 
> Then run `docker build -t benbusby/whoogle-search:workaround .` to build this image. It is now runnable.
> 
> Now you can `docker run ... benbusby/whoogle-search:workaround`

Why not make a pull request?

**Comment by eddydc** [comment] 2021-05-18 05:23
What needs to happen next in order to have this pull request in the docker image in order to have this available (for Synology)?

**Comment by LivingWithHippos** [comment] 2021-05-18 08:03
> What needs to happen next in order to have this pull request in the docker image in order to have this available (for Synology)?

Wait for it to be closed

**Comment by bruvv** [comment] 2021-05-18 08:03
Wait for it to be merged*

**Comment by eddydc** [comment] 2021-05-18 08:09
And who can close/merge things or is responsible for this?

**Comment by bruvv** [comment] 2021-05-18 08:12
@benbusby can as he is the owner

**Closed** 2021-05-18 14:52 UTC
Labels: bug

**Comment by benbusby** [comment] 2021-05-18 15:01
@bruvv's fix has been merged, with a small modification to format the date in the cookie using the current datetime. I'm skeptical that there could be a timeout period associated with a static date used in the cookie, so using the current date should be a better alternative. The `latest`, `beta`, and `buildx-experimental` Docker tags will be updated once the CI build finishes.

**Comment by jeroen7s** [comment] 2021-05-21 12:31
when will tne new version be on Pip? :)

**Comment by benbusby** [comment] 2021-05-21 14:38
@jeroen7s soon, planning on having a new release out today.
