### ISSUE TITLE
[BUG] <cannot see IMAGES anymore>

### ISSUE THREAD

**Issue by imTHAI** [benbusby/whoogle-search#1080] opened 2023-10-11 08:13 UTC
**Describe the bug**
I'm using whoogle since 2 years. (I started with running my instance on Heroku until they stopped the free subscription. Now it's running on my unRAID server at home).
I discovered that when I click to go in the IMAGES "tab" of Whoogle after searching something, I get an error message. I cannot tell when it started exactly but it must be recent because I use it almost every day, since whoogle is configured as my main search engine.

**To Reproduce**
1. Search for someone (Let's say Rose Leslie)
2. Click on 'IMAGES'
3. See error

**Version of Whoogle Search**
v0.8.3

**Desktop (please complete the following information):**
- Im using Safari but I also tried with Brave.

Error message display in the browser:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Error in the logs of the container:
```
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/routes.py", line 124, in decorated
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/routes.py", line 59, in decorated
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/routes.py", line 316, in search
    response = search_util.generate_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/utils/search.py", line 167, in generate_response
    formatted_results = content_filter.clean(html_soup)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/filter.py", line 164, in clean
    for div in self.main_divs:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

```

**Comment by Afaren57** [comment] 2023-10-11 10:06
Same problem here

**Comment by benbusby** [comment] 2023-10-11 17:09
Sorry about that! Just pushed a fix.

**Closed** 2023-10-11 17:09 UTC
Labels: bug

**Comment by benbusby** [comment] 2023-10-11 17:17
@techcow2 how are you running Whoogle? If it's anything docker related, the images take about 20 minutes to build and deploy to docker hub.

**Comment by farline99** [comment] 2023-10-11 17:41
> Sorry about that! Just pushed a fix.

I updated to the latest version from Docker Hub and the problem is still there.

**Comment by imTHAI** [comment] 2023-10-11 18:19
Same for me. Update done (unRAID has detected there were a new version available), but I still have the problem.
The error message in the logs is the same:
```
ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/routes.py", line 124, in decorated
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/routes.py", line 59, in decorated
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/routes.py", line 316, in search
    response = search_util.generate_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/utils/search.py", line 167, in generate_response
    formatted_results = content_filter.clean(html_soup)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/whoogle/app/filter.py", line 164, in clean
    for div in self.main_divs:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by farline99** [comment] 2023-10-12 14:01
yup, it works now 🙂❤️
