### ISSUE TITLE
[BUG] New update not fixing old problem

### ISSUE THREAD

**Issue by Rowan-Bird** [benbusby/whoogle-search#262] opened 2021-04-04 17:56 UTC
The problem i've experienced before hasn't been fixed, yet a new version came (To be fair, the update notes only said "Bypass EU Cookie Consent") This is ridiculous

It's also happening when i'm going to the image search

This makes the software almost unusable

The string is still this
gAAAAABgafuVv1-a4ckdJfUDt2wOKvJh3SmkGb6Z9qKDt5W5GectNGh47rYlQVRQ1D7aqPYyXoWqfNahhCn7fyTmT9XsKl7Wsg==
Tell me if it's different, but i won't care

There was an opportunity to fix it between 0.3.1 and 0.3.2, and yes, i updated to 0.3.2, i'm using PIP on Windows 7, if this is an issue with python, i'm actually using python 3.6 (Again, windows 7) and that might be the issue, but i doubt it

**Comment by federicotorrielli** [comment] 2021-04-05 13:03
Can you explain better the problem? I can't really understand. The string you are seeing it's not a bug, but an encrypted path.

**Comment by benbusby** [comment] 2021-04-05 15:34
@federicotorrielli this is actually a bug with the query decryption process. Prior to `0.4.0`, queries were encrypted using a set of continuously regenerated keys tied to the user's session. For some reason, some users were experiencing an issue where the key regeneration step happened prior to page navigation, which is what was being used to generate a new set. I only had 2 reports of the bug ever happening, so I figured it was some edge case, but handled it in the latest release anyways. Now the decryption key set is static per user session.

@Rowan-Bird the bug fix you're referring to was not included in `0.3.2` (as you already saw). I typically don't release bug fixes until they've been tested in beta for a little while, or are relatively trivial (in the case of the EU consent cookie fix). I've been considering including a `whoogle-search-beta` pip package for this very reason, but haven't yet since the user count for pip is much lower than with other deployment methods. Since the fix for the bug you were encountering meant non-trivial changes, it was still being tested in beta until today. I should've been more specific when closing your initial issue about which release it would be included in (in this case, `0.4.0`) rather than *when* it would be included, since this often changes.

**Comment by bitfl0wer** [comment] 2021-04-05 18:14
I updated using `pip3 install whoogle-search` and checked that the installed version of whoogle-search is in fact 0.4.0, but the problem still appears on my end. 
<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/39242991/113608818-518f6e00-964b-11eb-86dc-316707d3663a.png">
<img width="167" alt="grafik" src="https://user-images.githubusercontent.com/39242991/113608938-771c7780-964b-11eb-91bb-69cf2e65fd84.png">

**Comment by benbusby** [comment] 2021-04-05 18:41
@bitfl0wer that is a separate issue which is being tracked in #243, not related to the OP's issue.

**Closed** 2021-04-12 14:04 UTC
Labels: bug
