### ISSUE TITLE
[FEATURE] I hope it supports Google Translate and Google Maps

### ISSUE THREAD

**Issue by Escher1108** [benbusby/whoogle-search#348] opened 2021-06-07 14:20 UTC
**Describe the feature you'd like to see added**
I hope it supports Google Translate and Google Maps，I hope it supports Google Maps and translation when I search. For example, when I use Google normally, I input "Google Translate" and the results are as follows:
[![2BkX6g.md.png](https://z3.ax1x.com/2021/06/07/2BkX6g.md.png)](https://imgtu.com/i/2BkX6g)

However, the whoogle search result looks like this
[![2BAJnH.md.png](https://z3.ax1x.com/2021/06/07/2BAJnH.md.png)](https://imgtu.com/i/2BAJnH)

**Additional context**
External reference:https://www.google.com/search?q=google+translate

**Comment by IniUe** [comment] 2021-06-10 09:32
Duplicate of #258
If you have time then submit a PR to replace with lingva instance (see past replacements about libreddit etc)

There's a problem for maps, you can ignore it https://github.com/benbusby/whoogle-search/issues/284

**Comment by IniUe** [comment] 2021-06-10 13:00
https://github.com/benbusby/whoogle-search/pull/180

**Closed** 2021-06-15 14:14 UTC
Labels: enhancement
