### ISSUE TITLE
[FEATURE] Add Libreddit to "Replace Social Media Links" for replacing Reddit links

### ISSUE THREAD

**Issue by hbarsaiyan** [benbusby/whoogle-search#220] opened 2021-03-08 19:38 UTC
**Describe the feature you'd like to see added**
Libreddit is an alternative private front-end to Reddit, like Invidious is for YouTube and Nitter is for Twitter. More information about it can be found [here](https://github.com/spikecodes/libreddit).

**Comment by benbusby** [comment] 2021-03-08 22:06
Duplicate of https://github.com/benbusby/whoogle-search/issues/172 -- libreddit is already available on the `develop` branch (and related Docker images).

**Closed by benbusby** 2021-03-08 22:06 UTC
Labels: enhancement
