### ISSUE TITLE
[BUG] Settings keep resetting

### ISSUE THREAD

**Issue by ThatOneCalculator** [benbusby/whoogle-search#661] opened 2022-02-17 23:56 UTC
**Describe the bug**
Seemingly by random, my settings keep getting reset

**To Reproduce**
1. Search a couple times
2. Settings get reset

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [v0.7.1]
- [ ] Not sure

**Instance:**
https://gowogle.voring.me

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Mozilla Firefox 97.0

**Comment by kapiorr** [comment] 2022-02-18 18:31
same for me:
in docker compose does not respect environment variables

**Comment by joonas-fi** [comment] 2022-03-05 10:41
I am observing behaviour like this as well

**Comment by jacr13** [comment] 2022-03-26 10:18
I'm experiencing the same behavior... The problem is that I didn't figure yet how to reproduce it. If someone manages to reproduce the bug consistently, please describe the procedure here, I would be happy to fix it and create I pull request.

**Comment by Messerr** [comment] 2022-04-30 23:18
> I'm experiencing the same behavior... The problem is that I didn't figure yet how to reproduce it. If someone manages to reproduce the bug consistently, please describe the procedure here, I would be happy to fix it and create I pull request.

I've noticed on firefox and ungoogled chromium if I right click highlighted text and hit "Search Whoogle for x" it resets all the settings I set on the main page. It also adds '&cookies_disabled=1' in the new search query when I do that.  I've added cookie delete exceptions etc. Not sure if my setup is correct but that's how I can replicate.

**Comment by hj-collab** [comment] 2022-05-05 15:10
@benbusby Hello Ben. Do you have any idea what is the cause for this issue? Any solution?

**Comment by Fxzzi** [comment] 2022-05-05 15:38
I am also experiencing this on my local instance of Whoogle from the AUR. The page loads fine for me without the cookies_disabled flag, but if I click on my whoogle link on my personal html startpage, it redirects me to http://localhost:5000/?cookies_disabled=1, even though the link that should be opened is just http://localhost:5000/

**Comment by MadcowOG** [comment] 2022-05-06 00:51
Is everyone here referring to the configuration settings at the bottom of the home page?

**Comment by benbusby** [comment] 2022-08-01 16:32
I believe this should be fixed as of f5d599e7d225fd2bc5ced234e172ce3ea8f6306f (included in v0.7.3), which addressed https://github.com/benbusby/whoogle-search/issues/749. From a bit of testing, this doesn't seem to be an issue with the latest versions since that fix, but please feel free open a new issue if the issue persists for any of you.

**Closed by benbusby** 2022-08-01 16:32 UTC
Labels: bug
