### ISSUE TITLE
[BUG] Before u continue to Google

### ISSUE THREAD

**Issue by anoo2niem** [benbusby/whoogle-search#1053] opened 2023-08-16 16:12 UTC
**Describe the bug**
Just since now, i'm not able to use whoogle anymore.  The google 'consent' page is popping up to allow or decline cookies.

**To Reproduce**
Search any keywoard

**Deployment Method**
Proxmox in lxc container

**Version of Whoogle Search**
8.2.0 (installed with script https://tteck.github.io/Proxmox/, which i guess uses pip, not sure)

**Additional context**
Tried changing vpn location where my instance is routed through

![image](https://github.com/benbusby/whoogle-search/assets/26277207/9f18873a-0874-4080-bc0f-6aea950dc393)

**Comment by Hydranet** [comment] 2023-08-16 16:21
I'm also getting the same with Whoogle running in a container, running the same version.

**Comment by rickykresslein** [comment] 2023-08-16 16:26
Same. This is a duplicate of #243, but that was from a couple of years ago. It seems this is a bug that keeps popping up when Google changes things.

**Comment by anoo2niem** [comment] 2023-08-16 16:49
Yeah the cause is surely on google's end. Probably it was/is a EU-only issue because of GDPR.
Hopefully this can be bypassed in some way.

**Comment by Syrox94** [comment] 2023-08-16 17:12
same here

**Comment by cpu2910** [comment] 2023-08-16 17:31
+1
Ubuntu Server 22.04 , Whoogle Docker v0.8.2

**Comment by anoo2niem** [comment] 2023-08-16 17:53
Current workaround; i've got my whoogle working again by routing it through a non EU vpn.

**Comment by helsingi** [comment] 2023-08-16 17:59
same issue

**Comment by NoCodeFromMe** [comment] 2023-08-16 18:17
Same, also located in the EU.
Debian 11, Pip, Whoogle Search v0.8.2

**Comment by imTHAI** [comment] 2023-08-16 18:26
Same here, from France

**Comment by chocology** [comment] 2023-08-16 18:26
same here from Bern

**Comment by Procuria** [comment] 2023-08-16 18:31
Can confirm too from Germany

**Comment by imTHAI** [comment] 2023-08-16 18:31
> Current workaround; i've got my whoogle working again by routing it through a non EU vpn.
Indeed. Thanks, it It will do the job in the meantime.

**Comment by fabi321** [comment] 2023-08-16 18:40
https://github.com/benbusby/whoogle-search/blob/18fc14dc5b6d898975d1e83134441c9976fc4f29/app/request.py#L310
It  looks like, the current style uses consent yes. However, If I try it out in a browser window, it always sets it to `Pending+###`, and also sets another cookie, `SOCS`, to `CAISHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg` (this is consistent across private browser sessions) Setting both of these resolved the issue in my case.

**Comment by cpu2910** [comment] 2023-08-16 18:46
> Current workaround; i've got my whoogle working again by routing it through a non EU vpn.

May I ask how and where to do this ?
My whoogle runs in a docker container on a ubuntu server nginx reverse proxy...

**Comment by anoo2niem** [comment] 2023-08-16 18:53
> > Current workaround; i've got my whoogle working again by routing it through a non EU vpn.
> 
> May I ask how and where to do this ? My whoogle runs in a docker container on a ubuntu server nginx reverse proxy...

I have a separate container running wireguard, and i point my whoogle container it's gateway to the ip of the wireguard container.  So set up a wireguard container and configure it according to your vpn provider, then make sure your iptables are set up right, so all network traffic comming in that container is forwarded properly.

**Comment by anoo2niem** [comment] 2023-08-16 19:02
> 

Would u mind explaining how to set these?
I want to try it aswell but i'm not sure how to modify that line.

**Comment by Imaskiller** [comment] 2023-08-16 19:24
Replacing 
`        cookies = {
            'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
                now.year, now.month, now.day
            )`

with 

`        cookies = {
            'CONSENT': 'PENDING+987',
            'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
            )`

fixes the problem.

**Comment by anoo2niem** [comment] 2023-08-16 19:35
> Replacing
> 
> ```
>         cookies = {
>             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
>                 now.year, now.month, now.day
>             )
> ```
> 
> with
> 
> ```
>        cookies = {
>             'CONSENT': 'PENDING+987',
>             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
>             ) 
> ```
> 
> fixes the problem.

Thanks, seems to have solved it indeed.

**Comment by C8opmBM** [comment] 2023-08-16 19:39
hopefully an update will be pushed soon. I have no idea how to edit those cookies lines :)

**Comment by mztiq** [comment] 2023-08-17 09:10
> > Replacing
> > ```
> >         cookies = {
> >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> >                 now.year, now.month, now.day
> >             )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```
> >        cookies = {
> >             'CONSENT': 'PENDING+987',
> >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> >             ) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes the problem.
> 
> Confirm that it solves the problem, but i needed to remove the ) on the end :-) otherwise i got a error: SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' on line 309

Can confirm.

**Comment by Sebastix** [comment] 2023-08-17 09:34
> Replacing
> 
> ```
>         cookies = {
>             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
>                 now.year, now.month, now.day
>             )
> ```
> 
> with
> 
> ```
>        cookies = {
>             'CONSENT': 'PENDING+987',
>             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
>             ) 
> ```
> 
> fixes the problem.

This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.

**Comment by Tubeman-cell** [comment] 2023-08-17 10:20
Getting the same thing

**Comment by C8opmBM** [comment] 2023-08-17 11:54
> > Replacing
> > ```
> >         cookies = {
> >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> >                 now.year, now.month, now.day
> >             )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```
> >        cookies = {
> >             'CONSENT': 'PENDING+987',
> >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> >             ) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes the problem.
> 
> This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.

Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users.  In advance, thanks

**Comment by cpu2910** [comment] 2023-08-17 12:10
> > > Replacing
> > > ```
> > >         cookies = {
> > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > >                 now.year, now.month, now.day
> > >             )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > with
> > > ```
> > >        cookies = {
> > >             'CONSENT': 'PENDING+987',
> > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > >             ) 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > fixes the problem.
> > 
> > 
> > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> 
> Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks

You may edit your running container:
docker exec -it <container_id> /bin/sh
edit the 'cookies'-line in ./app/request.py
exit the container and restart with 'docker restart <container_id>

That fixed the problem for me.

**Comment by bjornberfelo** [comment] 2023-08-17 12:32
> > > Replacing
> > > ```
> > >         cookies = {
> > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > >                 now.year, now.month, now.day
> > >             )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > with
> > > ```
> > >        cookies = {
> > >             'CONSENT': 'PENDING+987',
> > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > >             ) 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > fixes the problem.
> > 
> > 
> > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> 
> Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks

Anyone who what's a temp image to use :-)
blivius92/temp-whoogle:latest

**Comment by cemkur** [comment] 2023-08-17 13:45
> > > > Replacing
> > > > ```
> > > >         cookies = {
> > > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > > >                 now.year, now.month, now.day
> > > >             )
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > with
> > > > ```
> > > >        cookies = {
> > > >             'CONSENT': 'PENDING+987',
> > > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > > >             ) 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > fixes the problem.
> > > 
> > > 
> > > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> > 
> > 
> > Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks
> 
> Anyone who what's a temp image to use :-) blivius92/temp-whoogle:latest

you need to remove the fourth line on the replacing block which is just a     ) 
than it works.

**Comment by nagyrobi** [comment] 2023-08-17 13:54
And how about the rest of us who installed by `pip`?

**Comment by heinxyze** [comment] 2023-08-17 14:18
Same behaviour
latest Whoogle docker image running on QNAP NAS, Germany

**Comment by be-root** [comment] 2023-08-17 19:17
> And how about the rest of us who installed by `pip`?

nano /usr/local/lib/python3.11/dist-packages/app/request.py

Line 297:

297        cookies = {
298         'CONSENT': 'PENDING+987',
299         'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg'
300         }

**Comment by imTHAI** [comment] 2023-08-17 20:13
> And how about the rest of us who installed by `pip`?

If it is confirmed that it solves the problem, why don't we apply the modification in the official branch ? Some extra tests must be performed ?

**Comment by fabi321** [comment] 2023-08-17 21:15
@imTHAI I already created #1054, it's just waiting to be merged

**Comment by fusrohdan** [comment] 2023-08-18 05:46
> > > > Replacing
> > > > ```
> > > >         cookies = {
> > > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > > >                 now.year, now.month, now.day
> > > >             )
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > with
> > > > ```
> > > >        cookies = {
> > > >             'CONSENT': 'PENDING+987',
> > > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > > >             ) 
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > fixes the problem.
> > > 
> > > 
> > > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> > 
> > 
> > Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks
> 
> You may edit your running container: docker exec -it <container_id> /bin/sh edit the 'cookies'-line in ./app/request.py exit the container and restart with 'docker restart <container_id>
> 
> That fixed the problem for me.

Hey, thanks for your fix.  I went to do this fix in my docker container, but there is no text editor available.  I tried vim and nano.  What text editor did you use?  I tried to see if the container has a volume mounted so I can edit from host but that is not the case. 
Thanks!

**Comment by JiriVitner** [comment] 2023-08-18 05:48
In the container is available "vi", not "vim"

**Comment by JiriVitner** [comment] 2023-08-18 05:48
> > > > > Replacing
> > > > > ```
> > > > >         cookies = {
> > > > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > > > >                 now.year, now.month, now.day
> > > > >             )
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > with
> > > > > ```
> > > > >        cookies = {
> > > > >             'CONSENT': 'PENDING+987',
> > > > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > > > >             ) 
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > fixes the problem.
> > > > 
> > > > 
> > > > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> > > 
> > > 
> > > Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks
> > 
> > 
> > You may edit your running container: docker exec -it <container_id> /bin/sh edit the 'cookies'-line in ./app/request.py exit the container and restart with 'docker restart <container_id>
> > That fixed the problem for me.
> 
> Hey, thanks for your fix. I went to do this fix in my docker container, but there is no text editor available. I tried vim and nano. What text editor did you use? I tried to see if the container has a volume mounted so I can edit from host but that is not the case. Thanks!


In the container is available "vi", not "vim"

**Comment by baerenmarke90** [comment] 2023-08-18 06:08
Workaround works, thank you!

**Comment by fusrohdan** [comment] 2023-08-18 06:13
> > > > > > Replacing
> > > > > > ```
> > > > > >         cookies = {
> > > > > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > > > > >                 now.year, now.month, now.day
> > > > > >             )
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > with
> > > > > > ```
> > > > > >        cookies = {
> > > > > >             'CONSENT': 'PENDING+987',
> > > > > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > > > > >             ) 
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > fixes the problem.
> > > > > 
> > > > > 
> > > > > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> > > > 
> > > > 
> > > > Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks
> > > 
> > > 
> > > You may edit your running container: docker exec -it <container_id> /bin/sh edit the 'cookies'-line in ./app/request.py exit the container and restart with 'docker restart <container_id>
> > > That fixed the problem for me.
> > 
> > 
> > Hey, thanks for your fix. I went to do this fix in my docker container, but there is no text editor available. I tried vim and nano. What text editor did you use? I tried to see if the container has a volume mounted so I can edit from host but that is not the case. Thanks!
> 
> In the container is available "vi", not "vim"

Thank you, I have edited the cookies line now but the container won't start.  I will troubleshoot later after work

**Comment by GusGus68** [comment] 2023-08-18 08:19
> > > > > > > Replacing
> > > > > > > ```
> > > > > > >         cookies = {
> > > > > > >             'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
> > > > > > >                 now.year, now.month, now.day
> > > > > > >             )
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > with
> > > > > > > ```
> > > > > > >        cookies = {
> > > > > > >             'CONSENT': 'PENDING+987',
> > > > > > >             'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 
> > > > > > >             ) 
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > fixes the problem.
> > > > > > 
> > > > > > 
> > > > > > This change also fixed it for me and I've manually build the Docker image (see https://github.com/benbusby/whoogle-search#manual-docker) to start a new container with it.
> > > > > 
> > > > > 
> > > > > Could you share your docker image until the official one is updated? I've never built an image and Im sure this will come handy for a lot of other users. In advance, thanks
> > > > 
> > > > 
> > > > You may edit your running container: docker exec -it <container_id> /bin/sh edit the 'cookies'-line in ./app/request.py exit the container and restart with 'docker restart <container_id>
> > > > That fixed the problem for me.
> > > 
> > > 
> > > Hey, thanks for your fix. I went to do this fix in my docker container, but there is no text editor available. I tried vim and nano. What text editor did you use? I tried to see if the container has a volume mounted so I can edit from host but that is not the case. Thanks!
> > 
> > 
> > In the container is available "vi", not "vim"
> 
> Thank you, I have edited the cookies line now but the container won't start. I will troubleshoot later after work

The reason it won't start is the last bracket. If you remove it it will work.

For any other noobs like me, the way to do this in docker is as per the instructions above. ssh into your server. then type 
docker exec -it <container_id> /bin/sh
cd app
vi request.py

then replace   
cookies = {
            'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(
                now.year, now.month, now.day
            ) 

with the following
  cookies = {
            'CONSENT': 'PENDING+987',
            'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg' 

note the last bracket is removed

Then exit and restart container with 
docker restart <container_id>

**Comment by IvanVojtko** [comment] 2023-08-18 09:18
Not the nicest one, but for my fellow kubernetes folks out there, update your deployment with
```
command: ["/bin/sh"]
args: ["-c", "sed -i '312d' app/request.py && sed -i \"s|'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(|'CONSENT': 'PENDING+987',|g\" app/request.py && sed -i \"s|now.year, now.month, now.day|'SOCS': 'CAESHAgBEhIaAB'|g\" app/request.py && misc/tor/start-tor.sh & ./run"]
```

**Comment by Luxumbra27** [comment] 2023-08-18 09:52
Little correction:
```
args: ["-c", "sed -i '312d' app/request.py && sed -i \"s|'CONSENT': 'YES+cb.{:d}{:02d}{:02d}-17-p0.de+F+678'.format(|'CONSENT': 'PENDING+987',  |g\" app/request.py && sed -i \"s|now.year, now.month, now.day|'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg'|g\" app/request.py && sed -i \"s|            )||g\" app/request.py && misc/tor/start-tor.sh & ./run"]
```

**Comment by Drallas** [comment] 2023-08-18 15:12
I run a LXC with Whoogle and struggled a bit, with service not starting 

`systemctl stop whoogle.service`

`vi /usr/local/lib/python3.11/dist-packages/app/request.py`

Then replaced the complete 'cookies block' for:

```
        # view is suppressed correctly
        now = datetime.now()
        cookies = {
            'CONSENT': 'PENDING+987',
            'SOCS': 'CAESHAgBEhJnd3NfMjAyMzA4MTAtMF9SQzIaAmRlIAEaBgiAo_CmBg'
        }
```

`systemctl start whoogle.service`
`systemctl status whoogle.service`

**Comment by Hydranet** [comment] 2023-08-18 16:31
> Then exit and restart container with
> docker restart <container_id>

This will only work if you are using persistent storage for your Whoogle container.

I tried the edit shown in the most recent pull request in my container but I still get the same "Before You continue to Google" page.
I replace  it with this.
```
cookies = {           
           'CONSENT': 'PENDING+987',                                   
           'SOCS': 'CAESHAgBEhIaAB',        
        }  

Is a restart of Whoogle needed to activate the changes?
```

**Comment by Hydranet** [comment] 2023-08-19 06:02
> Anyone who what's a temp image to use :-)
> blivius92/temp-whoogle:latest

I just tried @bjornberfelo's temp image and it works, thank you!  Which means that  if you are running the official image and change the lines manually in your image that your container needs a restart which means you need to be using persistent storage for your container or else your container will revert to the image you are using when you restart your container.

**Comment by sven-hash** [comment] 2023-08-19 17:14
I've juste rebuild the image with the modification and it solved the error
The docker image is published here if anyone want to use it [https://hub.docker.com/r/notrustverify/whoogle-search](https://hub.docker.com/r/notrustverify/whoogle-search)

**Comment by malyyigor34** [comment] 2023-08-20 15:31
Confirm issue, I am from Poland

**Comment by HeavyTobi** [comment] 2023-08-21 07:32
same issue for me, 

Germany
Whoogle v0.8.2
Server: Docker @ Ubuntu LTS
Clients tested: Firefox on macOS and Safari on iOS

**Comment by Deedikjupijn** [comment] 2023-08-21 14:43
Same issue here, 
Just installed whoogle, 
Server: Docker debian 11

**Comment by DrMatschhirn** [comment] 2023-08-21 15:07
Same Issue with latest Docker Image.

**Comment by peternrdstrm** [comment] 2023-08-21 20:02
I have the same issue but with Heroku. Can somebody help me do the workaround?

**Closed** 2023-08-21 20:50 UTC
Labels: bug

**Comment by martyn-meister** [comment] 2023-08-22 09:58
Latest docker image works for me.  Remember to do a docker pull, or in k8s `ImagePullPolicy: Always` or you won't get the newest.

**Comment by sorcer1122** [comment] 2023-09-13 22:18
Had the same problem in Amsterdam. The following fixed it:
docker pull benbusby/whoogle-search
docker stop [container_id]
docker rm [container_id]
docker run --publish 5000:5000 --detach --name whoogle-search benbusby/whoogle-search:latest
