### ISSUE TITLE
[BUG] Safe search & image tab Style

### ISSUE THREAD

**Issue by Backup700** [benbusby/whoogle-search#80] opened 2020-05-26 12:13 UTC
The safe search is not disabling, even if i tried to untick & hit save. It reverts back to ON state.
Please look at this issue.

----
Also the image search tab opened on mobile browser looks out of current theme style.

**Comment by benbusby** [comment] 2020-05-26 16:49
Safe search issue is fixed as of 98d639883c4c83288e1b762439c6b3604f713a15.

Image search tab issue is not a bug since this has always appeared this way and is documented in the README. I'm about to add an issue for it though.

**Closed by benbusby** 2020-05-26 16:49 UTC
