### ISSUE TITLE
[BUG] Google often ask for cookie approval

### ISSUE THREAD

**Issue by Hunam6** [benbusby/whoogle-search#242] opened 2021-03-30 02:09 UTC
**Describe the bug**
Google often ask for cookie approval as seen is screenshots below.

**To Reproduce**
1. Install Whoogle
2. Search multiple times something until this error occurs
3.
![image](https://user-images.githubusercontent.com/38606542/112922420-5f516a80-9104-11eb-95e7-901a841b5d99.png)

**Deployment Method**
- [x] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.3.1
- [ ] Not sure

**Desktop:**
 - OS: Windows 10
 - Browser Brave
 - Version 1.24.29 Chromium: 90.0.4430.41 (Official Build) nightly (64-bit)

**Comment by benbusby** [comment] 2021-03-30 16:23
Duplicate of #243, moving conversation there.

**Closed by benbusby** 2021-03-30 16:23 UTC
Labels: bug
