### ISSUE TITLE
[FEATURE] Theme/color scheme/UI customization

### ISSUE THREAD

**Issue by edmael** [benbusby/whoogle-search#60] opened 2020-05-18 12:27 UTC
**Describe the feature you'd like to see added**
It would be nice to have the chance to edit the Logo/colors in homepage and hide the configuration option.
Basically if I run it on my server I'd like an easy way to give my search engine a nicer looking look and hide the "Configuration" line beneath it so if I share that URL people can search and not edit the options.

**Describe which parts of the project this would modify (front end/back end/configuration/etc)**
Mainly frontend, but maybe this can be integrated with #43

**Comment by ilovepancakes95** [comment] 2020-05-20 01:00
I second this request. Customization, especially at least major elements like logo would be great.

**Comment by BeecherNetworks** [comment] 2020-05-22 10:54
Thirded! In the meantime, you can do some customisation by copying the CSS file out of the container, editing it, and copying it back in again.

`docker cp whoogle:/usr/src/app/app/static/css/main.css .
vi main.css
docker cp main.css whoogle:/usr/src/app/app/static/css/main.css`

I changed the primary colour in Vim with `:%s/685e79/0069A8/g`, and added the following to the top to hide the logo and the customisation panel. (I also tried to hide **Whoogle** from the top of the results page but that hasn't worked, need to look at it again.)

`.logo, #config-collapsible, .cOl4Id { display:none !important }`

If you want to change the logo, copy yours to `/usr/src/app/app/static/img/logo.png`.

**Comment by edmael** [comment] 2020-05-22 13:16
> I changed the primary colour in Vim with :%s/685e79/0069A8/g, and added the following to the top to hide the logo and the customisation panel. (I also tried to hide Whoogle from the top of the results page but that hasn't worked, need to look at it again.)

I think that's because the result page use an inline css style and the logo seems to be wrapped in a .cOl4Id class. Don't know why is that, maybe @benbusby can shine some light on this.

**Comment by benbusby** [comment] 2020-05-22 17:47
Hiding the Whoogle logo should be as simple as adding `display: none !important` to the `.cOl4Id` class (which is a class used by Google, not controlled by me). Just tried it out and it works, but since I'm rewriting Google's inline styling in place, you'll have to load in your own stylesheet in  `display.html` (or add a line to import `main.css` with your changes).

I agree that this would be a nice feature, but it's not a huge priority just yet. I'd like to focus on core functionality before moving to aesthetic/preferential features, but I'm more than happy to accept any PRs implementing something like this. I don't imagine it would be too hard, and it sounds like you guys are already ahead of me on this front anyways!

**Comment by BeecherNetworks** [comment] 2020-05-23 08:52
So main.css is loaded on the homepage but not on the results page?

**Comment by benbusby** [comment] 2020-05-23 20:33
@BeecherNetworks correct

**Comment by benbusby** [comment] 2020-05-26 17:03
Pinning this issue so that anyone can see this first before suggesting that I add in a specific theme.

**Comment by BeecherNetworks** [comment] 2020-06-11 22:26
FYI, this is easier now as search.css is common to the landing and results pages. I'm sure the CSS or parent folder could be mounted as a volume, but for now you can just copy out search.css, add your changes and copy it back in again.

```
docker cp whoogle:/usr/src/app/app/static/css/search.css .
vi search.css
docker cp search.css whoogle:/usr/src/app/app/static/css/search.css
```

I added the following CSS to hide the logo, footer and config.

`.logo, .logo-div, #config-collapsible, footer { display:none !important }`

**Comment by benbusby** [comment] 2020-06-12 03:21
Great idea from @BeecherNetworks, but also worth mentioning that as of version 0.2.0 the config settings are now stored per session rather than only having a single config file per instance, so there shouldn't be a need to hide this anymore (unless you just don't want it shown in general).

**Comment by BeecherNetworks** [comment] 2020-06-12 15:37
Yes, I'm just hiding it for myself, once it's set I won't be changing it.

To save me the hassle of testing, do volumes needs to be preset in the Dockerfile, like ports, or can you just mount anything in the container?

**Comment by benbusby** [comment] 2020-07-09 16:25
Merging in #100 with this issue:

> Is it possible to remove the customize area? I wanna make this as easy as possible for my family to use. Will be used on our home server accessible by about 40 people in our family. I wanna keep them from messing with the settings.

> Would love to have the customize option via the private network web ui and not on the public facing part.

> After reading another issue post by another user I see where you state how to hide the customize area. Would still love to see it like for private facing.

**Comment by zhdenny** [comment] 2020-08-19 14:35
The included Whoogle Dark theme makes it REALLY hard to read previously visited site titles. Do you guys agree? How do I fix this via css edit? I tried but nothing worked and this is so annoying it is preventing me from using the Dark Theme entirely

![vivaldi_2020-08-19_10-32-51](https://user-images.githubusercontent.com/26662131/90648509-9c1cc100-e207-11ea-9a54-ef267bf545f2.png)

**Comment by benbusby** [comment] 2020-08-20 19:02
Yeah the dark theme needs work for sure. I've been putting off working on it for a while since my (limited) time is better spent on fixing or adding functionality to the tool. I'm still holding out hope that someone jumps in to add in theme customization soon.

Anyways, the visited link color is a color added inline by google when being passed back through to the client

```css
a:visited {
    color: #4B11A8;
}
```

Overriding that style with whatever you prefer would get rid of this issue, though it's not really a satisfactory workaround. I personally stopped using the dark theme a while back and wrote a custom theme for DarkReader that works a lot better in my opinion, at least as a temporary solution until this gets implemented. 

The DarkReader theme is applied as a static (not dynamic) theme on top of the default whoogle theme (not the dark one), and looks like this:

![image](https://user-images.githubusercontent.com/33362396/90813658-1ff8ab00-e2e5-11ea-9a25-4fd5046d6492.png)

CSS here:

```css
html {
  background-color: #000 !important;
}

body {
  background-color: #222 !important;
}

div {
  background-color: #111 !important;
  color: #fff !important;
}

a h3 div {
  color: #9999ff !important;
}

a div {
  color: #aaffaa !important;
}

div span {
  color: #bbb !important;
}

input {
  background-color: #111 !important;
  color: #fff !important;
}
```

**Comment by benbusby** [comment] 2020-08-20 19:35
Since I had a free moment, I actually went ahead and implemented a new dark theme based on the one mentioned above. The new dark theme uses a dedicated stylesheet for all color replacements, rather than relying on the filter process, and as a result should be much easier to edit for anyone looking to customize it in a hurry. Could still be improved upon most likely, but at least it's something I'd consider usable now.

If anyone wants to check out the branch (`feature/new-dark-theme`) and see it for themselves and/or add suggestions, feel free. If all looks good as a temporary solution, I'll merge it to dev.

**Comment by devn3t** [comment] 2020-09-26 01:04
The only thing keeping me from using Whoogle instead of Searx at this point in time is the width not being adjustable.  It looks tiny and horrible on a widescreen monitor and it makes me cringe every time I visit my search results.

Theming would be nice...I wouldn't be mad at it.

**Comment by benbusby** [comment] 2021-03-21 01:26
Custom CSS styling and theming is now included as a config option with #227. The github wiki has also been updated (see [here](https://github.com/benbusby/whoogle-search/wiki/Styling-with-Custom-CSS) and [here](https://github.com/benbusby/whoogle-search/wiki/User-Contributed-CSS-Themes)) with a guide for changing color schemes and the (short) list of contributed user themes. Additionally since the inclusion of custom CSS extends beyond just color theming, result widths can be tailored to a user's liking as well (see the wiki for an example). Fine grained control of the UI is still a bit difficult since the element class names are obfuscated by google, but isn't too terrible to work around with some patience and "inspect element".

**Closed by benbusby** 2021-03-21 01:26 UTC
Labels: enhancement

**Comment by xLeon-python** [comment] 2021-07-11 17:24
The dark theme does not change the colour of the top stories:

![Unbenannt](https://user-images.githubusercontent.com/53626026/125204357-609a4380-e26c-11eb-82cd-c48ccc2bb1e6.PNG)

Taking a look at the DOM elements, all the stories have a class called "idg8be". Each card has the class "BVG0Nb" and changing the background-color of the element solves the problem

**Comment by gripped** [comment] 2021-07-12 07:55
Which browser are you using ?
I just tested on Firefox and Chromium on Linux, and Edge on Windows.
Still works as intended here. Firefox:
![Screenshot_20210712_084302](https://user-images.githubusercontent.com/3513053/125250636-66386d80-e2ee-11eb-9ca7-7eabb453841c.png)
You can see in that screenshot that .BVG0Nb has background-color set to --whoogle-dark-page-bg by dark-theme.css

**Comment by xLeon-python** [comment] 2021-07-15 18:13
I used an older version of firefox (V 87.0 to be exact). I tried reproducing it, but had no luck

**Comment by 7reont5pao** [comment] 2021-09-01 11:54
It'd be great if Whoogle could provide a standalone CSS class for the matched query so that it stands out (i.e. it's highlighted) in individual search results just like it does in Google, allowing one to see in what context the search appears.

**Comment by KaiDevrim** [comment] 2021-09-08 21:27
Have the ability to change the Whoogle display name or just hide it.

**Comment by jackyzy823** [comment] 2021-09-20 07:37
Configuration dialog cannot be closed in low DP mobiles.
For example like 360x600:
![screen](https://user-images.githubusercontent.com/2900871/133969498-0458eea4-98a3-4282-aee1-40125daede49.png)

**Comment by astier** [comment] 2021-10-13 02:54
## Problem

I would like to request a `minimal-mode`. I usually only want to see the results as:

- Title
- URL
- Description

Right now there are other elements which I don' like to see:

- Top Stories
- Twitter Feeds
- Related Searches
- People also Ask
- Summaries/Biographies (see Joe Biden, Albert Einstein and Long-Term-Short-Memory screenshots)
- Facts-List/Summaries of the respective websites (see Albert Einstein Facts screenshot with results which show his birthday, deathday, parents, education, etc. as a list below the result-description)

Some of this elements can be minimized like "People also Ask", some other I can block with the zapper-tool form ublock, but other like Summaries/Biographies I can not remove.

## Solution

`minimal-mode` option which if set reduces the results-list to only the titles, urls and descriptions of the respective results.

## Notes

I always liked the minimal look of startpage which only shows a list of results consisting from title, url, description. They have an instant-answer feature but there is an option to disable it.

This feature would reduce information-overload, visual clutter and for some people may be also more visual appealing.

If I want to see a biography and facts I click on the wikipedia result. If I want to see the tweeter-feed I open the twitter-result. If I want to see the images/news I click on the images/news-category, etc.

## Screenshots

### Joe Biden Summay and Top Stories

![joe_biden](https://user-images.githubusercontent.com/36510152/137058386-9a12b27e-203b-480c-9829-f9dbd2808a71.png)

### Long Short Term Memory with an Image-Feed

![lstm](https://user-images.githubusercontent.com/36510152/137058396-3f7e0921-d80a-49d6-959e-c18c618bcbca.png)

### Albert Einstein Summary with his books
![albert_einstein_summary](https://user-images.githubusercontent.com/36510152/137058407-ba66c4aa-4dc0-40bd-83a0-dbc1848d0f23.png)

### Albert Einstein with Facts-Lists under every result
![albert_einstein_facts](https://user-images.githubusercontent.com/36510152/137058422-5e9e4d9f-631d-4e50-bbd9-7c4f2cf45ba7.png)

**Comment by Brenders** [comment] 2022-01-22 23:15
hi i have a request about whoogle gui it is desktop mode, at this moment whoogle is with the graphics of the mobile version not very suitable for pc screens such as a 1080p or a 2k, 4k, etc. would it be possible to have the implementation of desktop mode?

**Comment by DUOLabs333** [comment] 2022-01-22 23:17
@Brenders I'm assuming this is due to the fact that the rows are short and centered in the middle, and not stretched out? If so, then there is a config for that.

**Comment by Brenders** [comment] 2022-01-23 00:12
I see the site like this
![Cattura](https://user-images.githubusercontent.com/83044464/150659536-fab085e1-49e0-4309-b892-fbcb1a1826c4.PNG)

**Comment by DUOLabs333** [comment] 2022-01-23 00:16
You want something like this:
```
WHOOGLE_CONFIG_STYLE=":root { /* LIGHT THEME COLORS */ --whoogle-background: #d8dee9; --whoogle-page-bg: #ffffff; --whoogle-accent: #2e3440; --whoogle-text: #3B4252; --whoogle-contrast-text: #eceff4; --whoogle-secondary-text: #70757a; --whoogle-result-bg: #fff; --whoogle-result-title: #4c566a; --whoogle-result-url: #81a1c1; --whoogle-result-visited: #a3be8c; --whoogle-element-bg: #685e79; /* DARK THEME COLORS */ --whoogle-dark-background: #222; --whoogle-dark-accent: #685e79; --whoogle-dark-text: #fff; --whoogle-dark-contrast-text: #000; --whoogle-dark-secondary-text: #bbb; --whoogle-dark-result-bg: #000; --whoogle-dark-result-title: #1967d2; --whoogle-dark-result-url: #4b11a8; --whoogle-dark-result-visited: #bbbbff; } body {max-width: 100% !important; /* or whatever width you want */} #whoogle-w { fill: #685e79; } #whoogle-h { fill: #685e79; } #whoogle-o-1 { fill: #685e79; } #whoogle-o-2 { fill: #685e79; } #whoogle-g { fill: #685e79; } #whoogle-l { fill: #685e79; } #whoogle-e { fill: #685e79; } "
```

**Comment by ThatOneCalculator** [comment] 2022-02-08 23:58
I'd really love to be able to add a custom logo, or even just change up the text!

**Comment by Waldorf3** [comment] 2022-05-02 21:43
> You want something like this:
> 
> ```
> WHOOGLE_CONFIG_STYLE="body {max-width: 100% !important; /* or whatever width you want */}"
> ```

I couldn't get this to work, the docker-compose kept complaining about the quotes. Ended up just adding 

body {max-width: 80% !important;

in the configuration - css box, and that was exactly what I wanted.

**Comment by LouA1** [comment] 2023-06-01 16:25
> I'd really love to be able to add a custom logo, or even just change up the text!

I second this option.  All I want to do is change Whoogle to Lougle.  How do I do it?

**Comment by moritzfl** [comment] 2023-07-19 08:37
I do believe the given examples are wrong. The following configuration worked for me:
```
    environment:
      - 'WHOOGLE_CONFIG_STYLE=body {max-width: 100% !important; }'
```

**Comment by glitsj16** [comment] 2023-10-16 03:56
Hi, the recently introduced search result icons (started in https://github.com/benbusby/whoogle-search/commit/4292ec7f636d51a5a150c094819a88db16c42627) work fine. I do appreciate all the work that's being done to keep whoogle-search in good condition, but I have to admit this new feature isn't adding anything value for me personally. Just as a matter of preference, I keep my web searching as unclutered/minimalistic as possible.

Realizing the work on this just started I wanted to ask if there's a knob planned to `disable` **favicons for each search result**? Is this something that's being considered?

For now I use user CSS in Firefox to remove them from view:

```css
.site-favicon {
    display: none !important;
}
```

But AFAICT the favicons are still being downloaded and that (slightly) slows things down.
