### ISSUE TITLE
Config Environment Variables not working

### ISSUE THREAD

**Issue by PaPaTheGMan** [benbusby/whoogle-search#839] opened 2022-09-02 15:37 UTC
I'm using various 'WHOOGLE_CONFIG' environment variables in my docker set up and only the 'THEME' seems to work.  I'm most interested in getting the 'NEW_TAB' as that is a great time saver for me but would like to see the others as well.

**To Reproduce**
Create a docker container as follows:
docker run -d \
  --name whoogle \
  -p 5080:5000 \
  -e WHOOGLE_CONFIG_COUNTRY="United States" \
  -e WHOOGLE_CONFIG_THEME=dark \
  -e WHOOGLE_CONFIG_NEW_TAB=true \
  --restart unless-stopped \
  benbusby/whoogle-search:latest

When accessing a Whoogle search only the Theme has been set, the other environment items as still at default.

**Deployment Method**
- [ X] Docker

**Version of Whoogle Search**
- [ X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ X] v0.7.4

**Desktop (please complete the following information):**
 - Windows 10
 - Browser = Edge, with Whoogle set as my default search (https://whoogle.mydomain.com/search?q=%s)
 - Version = 104.0.1293.70

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
Docker Container is running on an Intel Celeron 3865U (2) @ 1.800GHz - Ubuntu 22.04.1 LTS x86_64
Docker version is 20.10.17, build 100c701

**Comment by jacr13** [comment] 2022-09-07 13:03
I have looked at your issue and indeed there is a bug.
The problem is that as it is, whoogle only accepts 1 or 0 as (true and false) inputs.

I have done a fix for this and hope Ben can merge it soon =)

**Closed** 2022-09-07 18:54 UTC
Labels: bug

**Comment by PaPaTheGMan** [comment] 2022-09-07 19:47
Thank you so much for the update.  I can easily just change the config to 1/0's.  What about the text items like config_country, language, etc?

**Comment by jacr13** [comment] 2022-09-07 22:18
Ben has already merged the pull request, so just update your image, and it should work fine.

For the country, you should use US:
-e WHOOGLE_CONFIG_COUNTRY="US"

**Comment by jacr13** [comment] 2022-09-08 17:55
For the language, you need to specify it with lang_ first:
 -e WHOOGLE_CONFIG_LANGUAGE="lang_fr"  # for the interface (french)
 -e WHOOGLE_CONFIG_SEARCH_LANGUAGE="lang_en"  # for the search results (english)

**Comment by PaPaTheGMan** [comment] 2022-09-08 20:00
Thank you!
