### ISSUE TITLE
[FEATURE] Google Maps Alternative Open Street Map

### ISSUE THREAD

**Issue by matt-laird** [benbusby/whoogle-search#576] opened 2021-12-13 17:51 UTC
**Describe the feature you'd like to see added**
Having the option to use Open Street Map as an alternative to Google Maps, much like the other social network alternative options work.

**Comment by not-my-profile** [comment] 2021-12-20 15:57
Duplicate of  #182 and  #284.

**Closed** 2022-02-01 19:01 UTC
Labels: enhancement
