### ISSUE TITLE
[FEATURE] Currency conversion

### ISSUE THREAD

**Issue by Aikatsui** [benbusby/whoogle-search#129] opened 2020-10-05 05:05 UTC
1. Time
Whoogle display time in 24 format. search: pakistan time, google display it in AM/PM format

2. Currency conversation
This feature not available on whoogle. search: eur to usd
(You can attach cool component for that)

3. Weather
This feature not available on whoogle. search: pakistan weather or certain city weather
(You can ignore if difficult to implement)

4. Calculator
This feature not available for whoogle. search: calculator

(You may need to integrate other services if difficult to take from google)

So far i only expect solution for 1 and 2.

**Comment by accountForIssues** [comment] 2021-06-13 10:09
I think 2-4 are not possible to implement as Google loads this via javascript in the browser whereas Whoogle scrapes and parses the results from a no-javascript version of Google search results.

@benbusby I thought it was possible to view (basic) results to such queries (1-3) using Whoogle. I remember it worked some versions ago (maybe I misremember). Currently on the latest version, none seem to work. Using the same query on Google no-js page (`gbv=1`), they show basic results for the query.

Example queries;
- usd to gbp
- weather nyc
- time london
- 15*88
- dog in polish

Usually, the first `div` in the search results is the basic answer response to such queries. I know Google makes it difficult by randomizing the class names often but is it possible for Whoogle to detect/scrape these and show it ? Currently, it feels like they are being removed as all other results remain.

**Comment by IniUe** [comment] 2021-06-18 18:09
This may make delay to implement this feature but it's not a problem, if we can go to next level than to google search then it'll be better too while privacy friendly. so i like to add a comment (enhancement request) about 2 and 3. I guess there're many free data providing services sites and APIs. (If that sounds like forcing, there's no thing like you should implement, that's only suggestions to make this project better :smile:) 

**Currency conversation**
e.g. the search engine get data from morningstar and coinbase for cryptocurrency
https://developers.coinbase.com (Retrieve real-time or historical price information) that's only an example; not as suggestion to use it or particular api. i don't know about its usability and on limited environments etc or possible to scrape from sites.

i'm interest to see whoogle usable to view day/week/years currency statistics charts, contents from economic calendar and other details useful for particular field persons. it'll be amazing for other whoogle users.

**Weather**
I assume this feature hasn't worked when @Aikatsui opened this issue but now it seems work to show weather in specific country or city from weather.com

![image](https://user-images.githubusercontent.com/81799342/122598831-8da56d00-d097-11eb-8999-cbafb022e43c.png)
![image](https://user-images.githubusercontent.com/81799342/122599147-11f7f000-d098-11eb-92cc-29905cfd589d.png)

It'll be better if it also able to display past and future weather details UI and some other useful contents.

About "**Calculator**"
This doesn't need to fetch any remote data or connect to anywhere. I think you may able to add a built-in powerful calculator that has many facilities and work perfectly with web-apps to use with desktop and mobile web browsers.

Thank you for develop whoogle. :1st_place_medal: we like it alot :+1:  app-0.5.0

**Comment by benbusby** [comment] 2021-09-15 22:14
Closing, since the issue is quite old at this point, and each of the OP's queries for basic currency conversion, weather, etc seem to all be working as expected.

**Comment by itsnotsaved** [comment] 2021-11-02 09:29
> Closing, since the issue is quite old at this point, and each of the OP's queries for basic currency conversion, weather, etc seem to all be working as expected.

@benbusby Request to reopen, currency conversation doesn't work

![image](https://user-images.githubusercontent.com/73447325/139820909-d6354480-8e09-46a0-9c8b-eb58eb67c4fd.png)

![image](https://user-images.githubusercontent.com/73447325/139820963-785478a3-9d1f-42ea-890b-dc9277bb0164.png)

**Comment by itsnotsaved** [comment] 2021-11-02 09:42
@accountForIssues has said,
> I think 2-4 are not possible to implement as Google loads this via javascript in the browser whereas Whoogle scrapes and parses the results from a no-javascript version of Google search results.

if not possible, may be you can integrate any good solution as @urynon said,

> Currency conversation
e.g. the search engine get data from morningstar and coinbase for cryptocurrency
https://developers.coinbase.com (Retrieve real-time or historical price information) that's only an example; not as suggestion to use it or particular api. i don't know about its usability and on limited environments etc or possible to scrape from sites.
i'm interest to see whoogle usable to view day/week/years currency statistics charts, contents from economic calendar and other details useful for particular field persons. it'll be amazing for other whoogle users.

**Comment by itsnotsaved** [comment] 2021-11-02 10:04
I saw these resources,
https://exchangerate.host/
https://github.com/exchangeratesapi/exchangeratesapi and it is deployable to heroku etc as whoogle.
(as i see its cloud service 250 requests/m free https://exchangeratesapi.io/) and not sure if that a good idea to integrate "exchangeratesapi" but no public instances as libreddit, lingva etc except exchangeratesapi.io

**Comment by vacom13** [comment] 2021-11-07 16:22
@benbusby I would like to give a more fully featured currency conversion a try.  Basically, as we discussed in the mention above, I would use the `regex` to identify whether `search query` includes such a request for conversion. If its true, I could basically just get the `first card` from `response` and use the numbers 
![example](https://user-images.githubusercontent.com/69755265/140652548-6aa3d5e8-db31-44e5-bcb2-067bd04e469c.jpg)
in it and create my own conversion factor which I could then use for the input boxes shown below

![example 2](https://user-images.githubusercontent.com/69755265/140652503-2dba2e9b-f8b0-4694-a960-5783ebcfd438.jpg)
then, I could code up some basic js for the same to allow for such conversions within the input box. As for knowing whether the user asked for a conversion, I was thinking of creating a json file with country currency codes in it so that the regex can use those. Does this make any sense?

**Comment by benbusby** [comment] 2021-11-07 17:52
@vacom13 yeah, that all sounds correct I think. As long as the JS you write is all self-contained (i.e. doesn't rely on external libraries) that should work great. I'm guessing a simple way to do that would be to use the ratio found in the original query -- for example 1:74.19 -- and use that to calculate new results for all subsequent values the user enters into the input box. If you want to rely on an external service though, you'd need to offload the calculation to the server instead, and just use JS to query for results.

**Comment by vacom13** [comment] 2021-11-07 17:56
@benbusby I was thinking of simply using the ratio to avoid using external services

**Comment by benbusby** [comment] 2021-11-07 18:26
@vacom13 yep, that sounds great

**Comment by vacom13** [comment] 2021-11-11 14:20
@benbusby just an update. I was thinking of making the regex when it hit me that a better way might be to just check for the disclaimer link in the first card of the search results and matching the `href` to `https://g.co/gfd` if it exists as surely, all the conversion queries which display this card would have it. Thereby accounting for all possible combinations effectively I think 😅.

![Disclaimer](https://user-images.githubusercontent.com/69755265/141313287-9f17d3ee-fa32-4ad1-ab37-48528b754f0a.jpg)

![hrefy](https://user-images.githubusercontent.com/69755265/141313590-9611a9d1-53b9-41a9-9302-b1a489cc678a.jpg)

**Comment by vacom13** [comment] 2021-11-13 18:00
@benbusby I keep getting this error please help.

![Eror_3.png](https://user-images.githubusercontent.com/69755265/141654157-a45a9d16-3858-401e-8588-cbc5be381e04.png)

The `second one` is what concerns me. It doesnt allow me to run the js function for some reason.

The code I wrote still needs to be improved 😅 but here it is.

![Code.jpg](https://user-images.githubusercontent.com/69755265/141654253-f1b92f5a-518d-43c1-8ff6-26c9f05a06d6.jpg)

![Js.jpg](https://user-images.githubusercontent.com/69755265/141654261-71a0b7ea-88a0-417b-9820-ceece4039a0e.jpg)

**Comment by benbusby** [comment] 2021-11-13 20:32
@vacom13 you might want to disable the CSP while you're developing this. There's another issue in the backlog for removing it entirely, which I agree with, just haven't had a sec to do it yet. The line you'd want to remove is `    resp.headers['Content-Security-Policy'] = app.config['CSP']` in `app/routes.py`. It should stop giving you that error afterwards. I'll go through and more thoroughly remove it sometime this weekend and then you can merge that change into your branch.

**Comment by vacom13** [comment] 2021-11-15 12:34
@benbusby okay great!

**Comment by vacom13** [comment] 2021-11-17 05:14
@benbusby I have the feature down. Maybe I could just create a pr and you can check?

**Comment by benbusby** [comment] 2021-11-18 02:34
@vacom13 for sure! Open a PR whenever you're ready

**Closed** 2021-12-07 05:56 UTC
Labels: enhancement
