### ISSUE TITLE
[BUG/FEATURE] Bypass EU cookie consent

### ISSUE THREAD

**Issue by Suika** [benbusby/whoogle-search#243] opened 2021-03-30 02:18 UTC
**Describe the bug**
I use proxy setup that rotates the proxing in the background and from time to time, when I connect to EU in this particular instance DE, whoogle will display a "Cookie consent" form from google.
After reloading the pages 2-3 times it vanishes, nonetheless it shows up every ~1-3 request via the addressbar search.

**To Reproduce**
1. Add you instance to your browser, in my case ungoogled-chromium
2. Either proxy or VPN the instance to the EU(DE)
3. Perform a serach via the url bar

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Win/Linux]
 - Browser [ungoogled-chromium]
 - Version [88.0.4324.182]

**Additional context**
![I want non-consensual google search](https://user-images.githubusercontent.com/2320837/112923388-bb64c080-90fd-11eb-959a-334f82fbb6ad.png)

**Comment by readall** [comment] 2021-03-30 16:11
This seems some kind of change from goog. I am also facing the same on my docker instance.

**Comment by Hunam6** [comment] 2021-03-30 16:30
> I assume your instance is also running in the EU?

Mine too

**Comment by benbusby** [comment] 2021-03-30 17:10
From a cursory bit of testing, it looks like accepting this dialog sets a `CONSENT` cookie with a value that roughly matches the following format `YES+[country code].[language]+[V#]+[B?]+[###]`.

Examples:

Netherlands (UK English) -- `CONSENT: YES+NL.en-GB+V9+BX+723`

Sweden (Swedish) -- `CONSENT: YES+SE.sv+V10+B+256`

I tried manually swapping the Sweden and Netherlands cookies, and it didn't seem to have a problem with that, so I'm curious if there's just a default value that can be set in `requests.send()` to bypass this altogether. Unfortunately it seems that whatever cryptic method they're using to generate the exact cookie value isn't easily accessible, but that might not be an issue (for now). 

I'll try to look into this some more soon. Thanks everyone for reporting it!

**Comment by Suika** [comment] 2021-03-30 23:32
@benbusby ok, here is a strange one. Set cookie `CONSENT=PENDING+600` and you should be fine for as many queries as you can do. Set it to ~220 you might get a consent page, set it to <=210 and you will always get the consent page. Max is 999 and it seems to be doing fine, anything higher resets the number to 060.

Don't explicitly know how it is tied together, but that one cookie seems to keep the consent away for a duration of time.

**Comment by readall** [comment] 2021-03-31 06:21
> @benbusby ok, here is a strange one. Set cookie `CONSENT=PENDING+600` and you should be fine for as many queries as you can do. Set it to ~220 you might get a consent page, set it to <=210 and you will always get the consent page. Max is 999 and it seems to be doing fine, anything higher resets the number to 060.


@Suika if you don't mind, where is code can this setting be done. I would like to try that.

**Comment by pYFZOS5** [comment] 2021-03-31 09:43
this happen on heroku EU instances and tested https://whoogle.himiko.cloud/ instance. it doesn't happen always just sometimes.
currently i solve this by come-back to homepage and re-search again or search other thing (then search old thing again), if searched multiple words contained something then search the main idea within one word etc. something no luck.
but that happen often so came to whoogle repo to report (or see if others already experience this)

**Comment by Suika** [comment] 2021-03-31 10:59
> 
> 
> > @benbusby ok, here is a strange one. Set cookie `CONSENT=PENDING+600` and you should be fine for as many queries as you can do. Set it to ~220 you might get a consent page, set it to <=210 and you will always get the consent page. Max is 999 and it seems to be doing fine, anything higher resets the number to 060.
> 
> @Suika if you don't mind, where is code can this setting be done. I would like to try that.

Quick and dirty would be https://github.com/benbusby/whoogle-search/blob/develop/app/request.py#L210-L212 just slap another entry in like `'cookie': 'CONSENT=PENDING+999'`

**Comment by readall** [comment] 2021-03-31 12:21
> Quick and dirty would be https://github.com/benbusby/whoogle-search/blob/develop/app/request.py#L210-L212 just slap another entry in like `'cookie': 'CONSENT=PENDING+999'`
@Suika 
Thanks for this hack. In effect the cookie-consent appears for a very brief moment (like few mili seconds) and then the search results load. So the irritation is temporarily addressed.

**Comment by Suika** [comment] 2021-03-31 13:16
> 
> 
> > Quick and dirty would be https://github.com/benbusby/whoogle-search/blob/develop/app/request.py#L210-L212 just slap another entry in like `'cookie': 'CONSENT=PENDING+999'`
> > @Suika
> > Thanks for this hack. In effect the cookie-consent appears for a very brief moment (like few mili seconds) and then the search results load. So the irritation is temporarily addressed.

You saw that probably just after you changed it. That is normal. Any consequent searches should now show anything. At least it doesn't for me.

**Comment by benbusby** [comment] 2021-03-31 13:55
Just pushed a hotfix that includes @Suika's fix while I look into this a bit more. It's available on the `develop` and `heroku-app-beta` branches, as well as the `beta` and `buildx-experimental` images (once the CI build finishes).

**Comment by federicotorrielli** [comment] 2021-04-01 08:13
From today on it's not possibile anymore to search in EU, this pops up anytime on 0.3.1, can we get a new release? Thanks!

**Comment by Hunam6** [comment] 2021-04-01 08:23
@federicotorrielli
I'm using the `heroku-app-beta` branch as specified in the previous comment by @benbusby and it works as intended.

**Comment by jeroen7s** [comment] 2021-04-01 08:25
> From today on it's not possibile anymore to search in EU, this pops up anytime on 0.3.1, can we get a new release? Thanks!

same for me, it used to show every few searches, but now it shows every single time I click search.

**Comment by federicotorrielli** [comment] 2021-04-01 08:57
whoogle-beta isn't really working for me right now btw: 
![image](https://user-images.githubusercontent.com/31370059/113269697-0129b080-92d9-11eb-8137-19f1aab73e59.png)

**Comment by Hunam6** [comment] 2021-04-01 09:15
@federicotorrielli I can relate, I have this bug since I updated my fork.
This bug was introduced here: https://github.com/whoogle-mirror/whoogle-search/compare/449999d5...282208f7

**Comment by gpopesc** [comment] 2021-04-01 09:30
use beta tag in docker compose or docker cli in order to pull the corresponding image.
the latest version 0.3.1 it doesn't work for EU users
it works for me
    _image: benbusby/whoogle-search:beta_

**Comment by xLeon-python** [comment] 2021-04-01 10:01
buildx-experimental works again, thanks.

docker pull benbusby/whoogle-search:buildx-experimental
docker run --publish 5000:5000 --detach --name whoogle-search benbusby/whoogle-search:buildx-experimental

**Comment by benbusby** [comment] 2021-04-01 14:28
The `heroku-app-beta` branch should be fixed now (minor regression, unrelated to this issue).

**Comment by inlophe** [comment] 2021-04-02 03:46
Is it just me or the beta and buildx-experimental docker tag stuck at starting for anyone else? I tried with both compose and run directly on 2 different servers and all stuck at starting then change to unhealthy after a while. But when I revert to the latest tag, it works (but with EU cookie consent ofc). Running it with -it produces the same log for latest and beta/buildx-experimental

**Comment by gpopesc** [comment] 2021-04-02 08:15
@inlophe no problem for me running beta version since yesterday
version: "3"
services:
  whoogle-search:
    image: benbusby/whoogle-search:beta
    container_name: whoogle-search
    ports:
      - 6051:5000
    restart: unless-stopped

**Comment by Suika** [comment] 2021-04-07 09:14
Sooo, did this fix it? Well, if the non-consensual searching ever breaks the only way will be, is to give consent https://github.com/ytdl-org/youtube-dl/commit/14f29f087e6097feb46bdb84878924bc410a57eb.
Unless there is a loophole. Either way, if fixed do close the issue?

**Comment by jeroen7s** [comment] 2021-04-07 09:17
Currently the 4.0 release seems to work again for me

**Comment by dr460nf1r3** [comment] 2021-04-07 09:25
I also did not experience issues after the fix was pushed, seems like it is indeed fixed

**Closed** 2021-04-07 14:21 UTC
Labels: bug
