### ISSUE TITLE
[BUG] Not reliable

### ISSUE THREAD

**Issue by LorisTecnology** [benbusby/whoogle-search#328] opened 2021-05-26 16:07 UTC
**Describe the bug**
Whoogle is not working as intended. I have to restart the service in order almost everytime

**Deployment Method**
cloned from source
**Version of Whoogle Search**
- [x] Latest build from [source]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave

**Comment by benbusby** [comment] 2021-05-26 16:32
Without a stack trace or any details at all to look at, there's nothing I can do with this. Why are you restarting it? Is "not working as intended" meant to mean that it's slow? Or that it isn't performing the search at all? If it's crashing, can you paste the stack trace? Any details would be helpful.

**Comment by LorisTecnology** [comment] 2021-05-26 16:44
whoogle keep loading without any result
how can i provide the stack trace?

**Comment by benbusby** [comment] 2021-05-26 17:17
If you built it and are running it from source, there would be a stack trace in whichever console you're running it from (if there's an error).

Does the home page load without issue? Or is it just searches that don't finish loading?

**Comment by LorisTecnology** [comment] 2021-05-26 17:20
the page keeps loading without showing any search

**Comment by benbusby** [comment] 2021-05-26 17:50
Whoogle isn't doing anything different per request, so that would indicate a network issue, or some other problem behind the scenes that I can't adequately debug without looking into your whole setup. It could be anything from a simple connectivity issue to Google throttling your instance specifically. I know some users in the past have had to whitelist Whoogle through their antivirus software (or something like that -- I don't use Windows often, and haven't investigated this problem personally yet). 

Since it doesn't seem related to Whoogle itself, I'm going to close this issue. I'm happy to try and help figure out what could be the issue, but you could also try deploying the app through one of the free alternatives (heroku or repl.it), or a public instance (although I don't monitor the reliability of any of those).

**Closed by benbusby** 2021-05-26 17:50 UTC
Labels: bug

**Comment by LorisTecnology** [comment] 2021-05-28 19:45
whoogle keep loading 
although the search is done

**Comment by astier** [comment] 2021-10-09 20:29
I just want to mention that I have the same issue. It doesn't happen most of the time but fairly often. The page loads for a long time before showing any results. After that whoogle handles new searches fine. Until it doesn't and it happens again. Its usable but kind of annoying. Maybe its not whoogles fault but still something is going on.

I have a similar issue with searx but not only with google but also with other search-engines. Searx eventually aborts the search with a timeout-error.

I write this just for the record. I don't expect it to be fixed. For now I am going back to google or startpage.

**Comment by working-name** [comment] 2024-04-20 14:24
Will add to this as well @benbusby - whoogle has a perpetuating issue for many versions now. I got here by searching to see if there's a quick fix. I get that there's a lot of variables at play but really... no, not so in my case. I didn't run a debug version of whoogle yet, but will have to, just in case it gives some insight.

Here's why I think it doesn't apply in my case:

- NPM (nginx proxy manager) is proxying the requests, and it gives me a gateway timeout if I leave it loading.
- NPM shows me logs of my request = networking is fine between me, my ISP, the host, the rack, the router, the switch, the cable up to my server ... you get the point.
- `docker stats #` shows me an essentially idle container for whoogle
- instance is private, it really should only be me using it
- if I restart the whoogle container with docker compose, it instantly works = there's no throttling by google (especially since it's not a public instance), there's no issue with NPM proxying the request since that is not restarted.

So all of those point to an issue happening within whoogle, there's not a lot of extraneous factors to worry about.

How often does it happen? I'd say ... 3-4 times per week. I have to log into my server and restart the container to make search great again. At times when I cannot ssh into my box because of draconian firewall rules at that location it will start working again on its own, but not sure how much time after (at least 1h).
