### ISSUE TITLE
Whoogle not detected as OpenSearch compatible for Chromium-based browsers

### ISSUE THREAD

**Issue by pluja** [benbusby/whoogle-search#112] opened 2020-07-31 11:07 UTC
**Describe the bug**
In order to set a "new search engine" on chromium-based browsers on Android (tested with [Bromite](https://bromite.org) and [Vanadium](https://github.com/GrapheneOS/Vanadium)) you need to visit an OpenSearch-compatible search engine and then it automatically appears on the "search-engine" list. Whoogle is not detected as a OpenSearch-compatible search engine even with having `/opensearch.xml`

**To Reproduce**
1. Go to `instance.whoogle.tld/search?q=%s`
3. Go to `Settings > Search Engine`
4. Whoogle should appear, but it's not appearing.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [x] `run` executable (systemd)
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [GitHub]
- [ ] Version [version number]
- [ ] Not sure

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android (GrapheneOS)
 - Browser: Chromium-based - Vanadium, Chromium
 - Version: Latest 84

**Comment by pluja** [comment] 2020-07-31 11:18
I've been testing and it seems is not a problem with only Whoogle. I will keep testing and get back with new info.

**Comment by TobiasDax** [comment] 2020-08-08 13:19
Also the `opensearch.xml` file can not be downloaded by firefoy to setup whoogle as a search engine.  
I guess this is connected, but i can not be sure since i have whoogle running in a docker.

**Comment by benbusby** [comment] 2020-08-15 20:06
I managed to figure this out after a bit of trial and error. It looks like Chrome doesn't allow opensearch templates to specify a `method` parameter alongside the search/suggestion URLs, even though it is [typically a supported parameter](https://github.com/dewitt/opensearch/blob/c897fc16f0d85b1da279ee232cc114a6dda4c1dc/mediawiki/Specifications/OpenSearch/Extensions/Parameter/1.0/Draft%202.wiki#the-url-element). I confirmed this manually, but there's also an indication that they only search GET requests [mentioned here](https://www.chromium.org/tab-to-search) (no explanation for why though).

Anyways, removing the `method=" {{ request_type }} "` section from the opensearch.xml template resulted in Chrome automatically importing the search engine (usually with search suggestion functionality as well, though this was hit or miss in the few times I tried it). 

I'm not sure to what extent this rule applies to other Chromium based browsers, since @botnet88 was able to get the default template working in ungoogled-chromium, but I've updated the template to exclude the method specification altogether if it isn't set to "post" (see e471b012a0ab302bf00bdd681e6f649f44ec0bd6). 

So if you're encountering this issue, try enabling the "GET requests only" config, then close your browser and re-open it to your Whoogle url. Chrome *should* then detect it as a valid opensearch format at that point. 

(@FoxxMD)

**Comment by FoxxMD** [comment] 2020-08-17 19:33
Thanks for the hard work Ben! I'm using the `beta` tag on dockerhub, I hope that one is up to date. With my chrome install I did:

1. Enabled get requests in config of whoogle instance
2. Removed manual whoogle entry from search engine settings
3. closed browser completely
4. re-opened and navigated to my url

Nothing happened -- should I see any indication that it "worked"?  I have re-added the manual entry for the time being.

**Comment by benbusby** [comment] 2020-08-17 20:30
There isn't any immediate visual indication, but it should appear in the list of available search engines after visiting the URL with the updated configuration -- at least, that's what happened for me. Could you verify that the opensearch template (`<whoogle url>/opensearch.xml`) doesn't contain a `method` parameter for the search/suggestion urls?

**Comment by FoxxMD** [comment] 2020-08-20 14:15
I can verify it does not have the method param but it's also not adding a search engine entry..

**Comment by benbusby** [comment] 2020-08-24 21:06
Ah okay. I'll revisit this again soon and see if I can't figure out more details.

**Comment by benbusby** [comment] 2020-11-19 00:40
Going to close this one now, as the discussion in #147 indicates that it has been fixed.

**Closed by benbusby** 2020-11-19 00:40 UTC
Labels: bug
