### ISSUE TITLE
[FEATURE] API for search?

### ISSUE THREAD

**Issue by Anduin2017** [benbusby/whoogle-search#1135] opened 2024-03-27 05:11 UTC
**Describe the feature you'd like to see added**
Is there any API that I can call whoogle to search and get search result?

**Additional context**
So I can use whoogle to develop other products which needs searching.

**Comment by benbusby** [comment] 2024-04-19 20:02
Duplicate of #607 (which is still planned, but not sure when it'll get done -- PRs encouraged)

**Closed by benbusby** 2024-04-19 20:02 UTC
Labels: enhancement
